// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADWNKqXMzw5KM9UaTbLRqbYxDJyufwglo',
    appId: '1:409552458210:web:29f96b081ca8a5583329bb',
    messagingSenderId: '409552458210',
    projectId: 'flutter-auth-67460',
    authDomain: 'flutter-auth-67460.firebaseapp.com',
    storageBucket: 'flutter-auth-67460.firebasestorage.app',
    measurementId: 'G-TPZ0Z1WK8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZcphVxx7yX691d4JDZVcq31sNZQUBgU',
    appId: '1:409552458210:android:50df97e2415284eb3329bb',
    messagingSenderId: '409552458210',
    projectId: 'flutter-auth-67460',
    storageBucket: 'flutter-auth-67460.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4o783q0Ho3h-sx2IZexRA9o7881QExOg',
    appId: '1:409552458210:ios:aeabe52ccc7563583329bb',
    messagingSenderId: '409552458210',
    projectId: 'flutter-auth-67460',
    storageBucket: 'flutter-auth-67460.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4o783q0Ho3h-sx2IZexRA9o7881QExOg',
    appId: '1:409552458210:ios:aeabe52ccc7563583329bb',
    messagingSenderId: '409552458210',
    projectId: 'flutter-auth-67460',
    storageBucket: 'flutter-auth-67460.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADWNKqXMzw5KM9UaTbLRqbYxDJyufwglo',
    appId: '1:409552458210:web:e4a06c7cba798f063329bb',
    messagingSenderId: '409552458210',
    projectId: 'flutter-auth-67460',
    authDomain: 'flutter-auth-67460.firebaseapp.com',
    storageBucket: 'flutter-auth-67460.firebasestorage.app',
    measurementId: 'G-79W9RNCQZG',
  );
}
